### PR TITLE
update to StaticArrayInterface

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
Closes #166

### CODE REVIEW

**Comment by ranocha** [comment]
Checking whether StaticArrayInterface.jl is registered now

**Comment by ChrisRackauckas** [comment]
v1.1 should help with the change, because of https://github.com/JuliaArrays/StaticArrayInterface.jl/pull/19

**Comment by ranocha** [comment]
We get some warnings
```
WARNING: Method definition getindex(ArrayInterfaceCore.ArrayIndex{N} where N, Union{Int64, Static.StaticInt{N} where N}, Union{Int64, Static.StaticInt{N} where N}...) in module ArrayInterface at /home/runner/.julia/packages/ArrayInterface/4RbA4/src/array_index.jl:23 overwritten in module StaticArrayInterface at /home/runner/.julia/packages/StaticArrayInterface/gJiae/src/array_index.jl:9.
```
and tests fail on latest stable Julia since we get `Int`s instead of static integers.

**Comment by ranocha** [comment]
I checked this locally. The problem is that `static_length(::SVector)` returns an `Int` while precompiling - while it should return a `StaticInt`. This works fine in a standard REPL session, but not at precompile time inside the `SnoopPrecompile.@precompile_all_calls` block
https://github.com/ranocha/SummationByPartsOperators.jl/blob/0206a74140d5c6eb9921ca5021cb7bf2da1a306d/src/precompile.jl#L4-L16

Any idea what's causing this, @ChrisRackauckas?

**Comment by ChrisRackauckas** [comment]
I don't know why that would happen. Sounds like a potential @timholy question if there's a known way that would be possible.

**Comment by ranocha** [comment]
The failing CI tests are using Julia v1.8. Extended precompilation in SummationByPartsOeprators.jl is only enabled on Julia v1.8 and newer. This explains why the Julia v1.6 tests pass.
The problem appears to be that StaticArrayInterface.jl uses Requires.jl to load the StaticArrays.jl extension on Julia v1.8, see 
https://github.com/JuliaArrays/StaticArrayInterface.jl/blob/b1aa4c000be289672a090b71c43a2ba1e439806f/src/StaticArrayInterface.jl#L487-L490
This happens in `__init__()` of StaticArrayInterface.jl. However, `__init__()` is not called at precompile time... Thus, the only option seems to call `StaticArrayInterface.__init__()` when precompiling SummationByPartsOeprators.jl manually - which is so hacky that I do not want to do it.

**Comment by ranocha** [comment]
I have no idea how to fix this so I asked on Discourse: https://discourse.julialang.org/t/how-to-load-require-jl-code-of-dependency-while-precompiling/95962

**Comment by ranocha** [comment]
Tests pass locally on Julia 1.9.0-rc1

**Pull request merged**
