### PR TITLE
fix addition of DerivativeCoefficientRows with different Start values

### PR DESCRIPTION
**Pull request by Dougal-s**
Adding together two `DerivativeCoefficientRow` variables with different `Start` values throws a bounds error.
For example,
```julia
import SummationByPartsOperators
row1 = SummationByPartsOperators.DerivativeCoefficientRow{Int, 0, 3}([1,2,3])
row2 = SummationByPartsOperators.DerivativeCoefficientRow{Int, 1, 3}([1,2,3])
row1 + row2
```
results in
```julia
ERROR: BoundsError: attempt to access NTuple{4, Int64} at index [0]
Stacktrace:
 [1] getindex
   @ ./tuple.jl:31 [inlined]
 [2] getindex
   @ ~/.julia/packages/StaticArrays/EHHaF/src/SArray.jl:62 [inlined]
 [3] +(coef_row1::SummationByPartsOperators.DerivativeCoefficientRow{Int64, 0, 3}, coef_row2::SummationByPartsOperators.DerivativeCoefficientRow{Int64, 1, 3})
   @ SummationByPartsOperators ~/.julia/packages/SummationByPartsOperators/DBpfT/src/SBP_operators.jl:149
 [4] top-level scope
   @ REPL[4]:1
```
After applying the fix, it returns
```julia
SummationByPartsOperators.DerivativeCoefficientRow{Int64, 0, 4}([1, 3, 5, 3])
```

### CODE REVIEW

**Review by ranocha — COMMENTED** [review]
Thanks for fixing this. Could you please add some unit tests as well to keep track of this?

**Comment by Dougal-s** [comment]
Sure thing! I wasn't sure where to put the unit tests, so I added them to the end of `linear_combinations_of_operators_test.jl`. Should I put them into a separate file instead?

**Review by ranocha — APPROVED** [review]
Thanks a lot!

**Comment by ranocha** [comment]
> Sure thing! I wasn't sure where to put the unit tests, so I added them to the end of `linear_combinations_of_operators_test.jl`. Should I put them into a separate file instead?

A new file would be fine 👍

**Review by ranocha — APPROVED** [review]

**Review by ranocha — APPROVED** [review]

**Pull request merged**
