### PR TITLE
Use default `arch` in CI

### PR DESCRIPTION
**Pull request by JoshuaLampert**
There are warnings (e.g., https://github.com/ranocha/SummationByPartsOperators.jl/actions/runs/12125109358?pr=307) in the CI runs because we request x64 on a macOS runner with arm64. I propose to simply use the default architecture, i.e. to remove the `arch` argument.

### CODE REVIEW

**Comment by JoshuaLampert** [comment]
Regarding the failing tests, see https://github.com/trixi-framework/P4est.jl/pull/135#issuecomment-2512286826.

**Comment by ranocha** [comment]
Could you please update this with option 2 from the other PR you linked above, i.e., 

> Exclude macos-latest for Julia v1.6 (and include macos-13 for Julia v1.6)

**Comment by ranocha** [comment]
I would like to keep this package working also for older versions of Julia if possible

**Comment by JoshuaLampert** [comment]
> > Could you please update this with option 2 from the other PR you linked above, i.e.,
> 
> Exclude macos-latest for Julia v1.6 (and include macos-13 for Julia v1.6)

Done in [658752d](https://github.com/ranocha/SummationByPartsOperators.jl/pull/308/commits/658752ddbdf1f3329f4c3773ee3dd4812b46c815).

**Comment by JoshuaLampert** [comment]
Ready for review @ranocha (remember to change the required CI checks).

**Review by ranocha — APPROVED** [review]
Thanks!

**Pull request merged**
